[package]
name = "print"
version = "0.1.0"
authors = ["NathanMcMillan54 <nathanmcmillan54@gmail.com>"]
edition = "2018"

[lib]
name = "print"
edition = "2018"
path = "src/lib.rs"
crate-type = ["staticlib"]
